{% set name = "lamin_utils" %}
{% set version = "0.13.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lamin_utils-{{ version }}.tar.gz
  sha256: b6c52a30079b4e797362b8e3c040821748d0174c7b1014d42274029ccfb4f582

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - packaging

test:
  imports:
    - lamin_utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/laminlabs/lamin-utils
  summary: Utils for LaminDB and Bionty.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - berombau
